name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Iliannnn
          template: classic
          base: activity, community, repositories, metadata
          config_twemoji: yes
          repositories: 250
          plugin_notable: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
